In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

In [2]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Roshini
[nltk_data]     D\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [4]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Roshini
[nltk_data]     D\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [7]:
df = pd.read_csv('ai_interview_dataset_large.csv', encoding='latin1')

In [8]:
df.head(10)

,Role,Question,Answer,Unnamed: 3
0,Data Scientist,What is Machine Learning?,This is a concise sample answer explaining: wh...,NaN
1,Data Scientist,Explain supervised learning.,This is a concise sample answer explaining: ex...,NaN
2,Data Scientist,Explain unsupervised learning.,This is a concise sample answer explaining: ex...,NaN
3,Data Scientist,What is overfitting?,This is a concise sample answer explaining: wh...,NaN
4,Data Scientist,What is underfitting?,This is a concise sample answer explaining: wh...,NaN
5,Data Scientist,What is feature engineering?,This is a concise sample answer explaining: wh...,NaN
6,Data Scientist,What is cross validation?,This is a concise sample answer explaining: wh...,NaN
7,Data Scientist,Explain bias vs variance.,This is a concise sample answer explaining: ex...,NaN
8,Data Scientist,What is a confusion matrix?,This is a concise sample answer explaining: wh...,NaN
9,Data Scientist,What is precision and recall?,This is a concise sample answer explaining: wh...,NaN

In [31]:
df.tail(10)

,Role,Question,Answer,Unnamed: 3
350,Full Stack Developer,Explain cloud hosting.,This is a concise sample answer explaining: ex...,NaN
351,Full Stack Developer,Explain logging strategies.,This is a concise sample answer explaining: ex...,NaN
352,Full Stack Developer,Explain monitoring systems.,This is a concise sample answer explaining: ex...,NaN
353,Full Stack Developer,Explain error tracking.,This is a concise sample answer explaining: ex...,NaN
354,Full Stack Developer,Explain documentation.,This is a concise sample answer explaining: ex...,NaN
355,Full Stack Developer,Explain code reviews.,This is a concise sample answer explaining: ex...,NaN
356,Full Stack Developer,Explain agile methodology.,This is a concise sample answer explaining: ex...,NaN
357,Full Stack Developer,Explain sprint planning.,This is a concise sample answer explaining: ex...,NaN
358,Full Stack Developer,Explain version control.,This is a concise sample answer explaining: ex...,NaN
359,Full Stack Developer,Explain DevOps collaboration.,This is a concise sample answer explaining: ex...,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Role        360 non-null    object
 1   Question    360 non-null    object
 2   Answer      360 non-null    object
 3   Unnamed: 3  1 non-null      object
dtypes: object(4)
memory usage: 11.4+ KB

In [11]:
df.shape

(360, 4)

In [12]:
df.duplicated().sum()

0

In [13]:
df.isnull().sum()

Role            0
Question        0
Answer          0
Unnamed: 3    359
dtype: int64

In [14]:
df.describe()

,Role,Question,Answer,Unnamed: 3
count,360,360,360,1
unique,12,352,359,1
top,Data Scientist,Explain scalability.,This is a concise sample answer explaining: wh...,This is a concise sample answer explaining: wh...
freq,30,3,2,1

In [15]:
import PyPDF2

In [16]:
import PyPDF2
def extract_text(pdf_path):
    text = ""
    with open(pdf_path,'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text()
    return text

In [17]:
resume_text = extract_text("Roshan_Data_Science.pdf")
print(resume_text[:500])

Roshan D
/linkedinRoshan |/envel⌢peroshan041703@gmail.com |♂¶obile(+91)8870102057
Summary
Entry-level Data Science professional with practical experience in machine learning, predictive modeling,
and data preprocessing through internship and academic projects. Proficient in Python, SQL, Pan-
das, NumPy, and Scikit-learn with hands-on experience building end-to-end ML pipelines, performing
exploratory data analysis, and improving model performance. Strong foundation in statistics, feature
enginee

In [18]:
skills_list=["python","machine learning","sql","data analysis","deep learning","cloud","docker","kubernets","excel","power bi","tableau","nlp"]
def extract_skills(text):
    text=text.lower()
    found=[]
    for skill in skills_list:
        if skill in text:
            found.append(skill)
    return found

In [19]:
skills = extract_skills(resume_text)
print("Detected Skills:", skills)

Detected Skills: ['python', 'machine learning', 'sql', 'data analysis', 'excel', 'power bi']

In [20]:
def detect_job_role(skills):
    if "machine learning" in skills or "nlp" in skills:
        return "Machine Learning Engineer"
    elif "sql" in skills and "excel" in skills:
        return "Data Analyst"
    elif "python" in skills and "deep learning" in skills:
        return "AI Engineer"
    else:
        return "Software Developer"

In [21]:
job_role = detect_job_role(skills)
print("Predicted Job Role:", job_role)

Predicted Job Role: Machine Learning Engineer

In [22]:
!pip install sounddevice

Requirement already satisfied: sounddevice in .\anaconda\envs\nlp\Lib\site-packages (0.5.5)
Requirement already satisfied: cffi in .\anaconda\envs\nlp\Lib\site-packages (from sounddevice) (2.0.0)
Requirement already satisfied: pycparser in .\anaconda\envs\nlp\Lib\site-packages (from cffi->sounddevice) (2.23)

WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)

In [23]:
!pip install scipy

Requirement already satisfied: scipy in .\anaconda\envs\nlp\Lib\site-packages (1.17.1)
Requirement already satisfied: numpy<2.7,>=1.26.4 in .\anaconda\envs\nlp\Lib\site-packages (from scipy) (1.26.4)

WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow (C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages)

In [24]:
data = pd.read_csv('fer2013.csv')
pixels = data['pixels'].tolist()
faces = []
for pixel_sequence in pixels:
    face = np.array(pixel_sequence.split(' '), dtype='float32')
    face = face.reshape(48,48)
    faces.append(face)
faces = np.array(faces)
faces = np.expand_dims(faces,-1)
faces = faces/255.0

In [25]:
import tensorflow as tf
import keras
import h5py

In [26]:
from tensorflow.keras.utils import to_categorical
emotions = pd.get_dummies(data['emotion']).values

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout

In [28]:
model = Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(48,48,1)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7,activation='softmax'))

C:\Users\Roshini D\anaconda\envs\nlp\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model.compile(
optimizer='adam',
loss='categorical_crossentropy',
metrics=['accuracy']
)

In [30]:
model.fit(
faces,
emotions,
epochs=10,
batch_size=64,
validation_split=0.2
)

Epoch 1/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 63s 131ms/step - accuracy: 0.3100 - loss: 1.7206 - val_accuracy: 0.4210 - val_loss: 1.5597
Epoch 2/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 54s 119ms/step - accuracy: 0.4206 - loss: 1.5048 - val_accuracy: 0.4720 - val_loss: 1.3851
Epoch 3/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 54s 120ms/step - accuracy: 0.4664 - loss: 1.3906 - val_accuracy: 0.5095 - val_loss: 1.2891
Epoch 4/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 53s 117ms/step - accuracy: 0.5079 - loss: 1.2992 - val_accuracy: 0.5188 - val_loss: 1.2467
Epoch 5/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 51s 113ms/step - accuracy: 0.5279 - loss: 1.2422 - val_accuracy: 0.5379 - val_loss: 1.2016
Epoch 6/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 52s 114ms/step - accuracy: 0.5530 - loss: 1.1784 - val_accuracy: 0.5521 - val_loss: 1.1739
Epoch 7/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 50s 112ms/step - accuracy: 0.5769 - loss: 1.1194 - val_accuracy: 0.5563 - val_loss: 1.1694
Epoch 8/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 55s 123ms/step - accuracy: 0.5949 - loss: 1.0703 - val_accuracy: 0.5698 - val_loss: 1.1492
Epoch 9/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 54s 120ms/step - accuracy: 0.6173 - loss: 1.0171 - val_accuracy: 0.5683 - val_loss: 1.1552
Epoch 10/10
449/449 ━━━━━━━━━━━━━━━━━━━━ 52s 115ms/step - accuracy: 0.6390 - loss: 0.9663 - val_accuracy: 0.5634 - val_loss: 1.1728

In [32]:
model.save("emotion_model.hdf5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [33]:
import cv2
from tensorflow.keras.models import load_model

In [34]:
emotion_model = load_model("emotion_model.hdf5", compile=False)

In [35]:
emotion_labels = [
"Angry",
"Disgust",
"Fear",
"Happy",
"Sad",
"Surprise",
"Neutral"
]

In [36]:
face_cascade = cv2.CascadeClassifier(
cv2.data.haarcascades+"haarcascade_frontalface_default.xml")

In [37]:
role_questions=df[df["Role"]==job_role]
question_row= role_questions.sample(1)
question=question_row["Question"].values[0]
correct_answer=question_row["Answer"].values[0]
print("Interview questions:")
question

Interview questions:

'Explain batch prediction.'

In [38]:
import threading
import sounddevice as sd
from scipy.io.wavfile import write

In [39]:
fs=44100
record_seconds=15
audio_data=[]

In [40]:
def record_audio():
    global audio_data
    print("Speak your answer...")
    audio_data = sd.rec(int(record_seconds * fs), samplerate=fs, channels=1,dtype='int16')
    sd.wait()
    write("answer.wav", fs, audio_data)
    print("Audio Recorded")

In [41]:
dtype='int16'

In [42]:
detected_emotion=[]
def emotion_detection():
    cap = cv2.VideoCapture(0)
    print("Camera on(press 'q'to stop)")
    
    while True:
        ret,frame=cap.read()
        if not ret:
            break
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        faces=face_cascade.detectMultiScale(gray,1.3,5)
        for (x,y,w,h) in faces:
            face=gray[y:y+h,x:x+w]
            face=cv2.resize(face,(48,48))
            face=face/255
            face=np.reshape(face,(1,48,48,1))
            prediction=emotion_model.predict(face)
            emotion=emotion_labels[np.argmax(prediction)]
            cv2.putText(frame,"Emotion:"+emotion,(x,y-10),
                    cv2.FONT_HERSHEY_SIMPLEX,0.8,(0,255,0),2)
        cv2.imshow("Interview Camera",frame)
        if cv2.waitKey(1)&0xFF==ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [47]:
audio_thread=threading.Thread(target=record_audio)
video_thread=threading.Thread(target=emotion_detection)
audio_thread.start()
video_thread.start()
audio_thread.join()
video_thread.join()

Speak your answer...
Camera on(press 'q'to stop)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Audio Recorded

In [48]:
import speech_recognition as sr

In [49]:
r = sr.Recognizer()

with sr.AudioFile("answer.wav") as source:
    audio = r.record(source)
try:
    candidate_answer = r.recognize_google(audio)
    print("\nCandidate Answer:", candidate_answer)
except:
    candidate_answer = ""
    print("Speech not recognized")

Candidate Answer: prediction is used to predict the accuracy value from the testing and training data to get the future outcomes

In [50]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to C:\Users\Roshini
[nltk_data]     D\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
stop_words=set(stopwords.words('english'))
def preprocess(text):
    tokens=word_tokenize(text.lower())
    filtered=[w for w in tokens if w not in stop_words]
    return " ".join(filtered)

In [54]:
def get_reference_answer(question):
    result = df[df["Question"] == question]

    if not result.empty:
        return result.iloc[0]["Answer"]
    else:
        return None

In [55]:
def evaluate_answer(candidate, reference):
    vectorizer = TfidfVectorizer()
    tfidf = vectorizer.fit_transform([candidate, reference])
    score = cosine_similarity(tfidf[0:1], tfidf[1:2])
    return round(score[0][0]*100, 2)

In [56]:
reference_answer = get_reference_answer(question)
print("Question:", question)
print("Candidate Answer:", candidate_answer)
print("Reference Answer:", reference_answer)
if reference_answer:
    score = evaluate_answer(candidate_answer, reference_answer)
    print("Score:", score, "%")
else:
    print("No reference answer found")

Question: Explain batch prediction.
Candidate Answer: prediction is used to predict the accuracy value from the testing and training data to get the future outcomes
Reference Answer: This is a concise sample answer explaining: explain batch prediction?Batch prediction (also known as batch inference or offline inference) in machine learning is the process of generating predictions for a large volume of data all at once, typically in a scheduled, non-real-time manner.
Score: 12.0 %